[package]
name = "transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"

[dev-dependencies]
test-case = "3.3.1"
